baseURL = 'https://atoz.mikiri.net/'
languageCode = 'ja'
title = 'Albums AtoZ by Mikirihassha P'
theme = "atoz"
hasCJKLanguage = true

[taxonomies]
  tag = "tags"
  category = "categories"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true